// Export Invoice config — column definitions, dropdown choices, and mock seed data
import { BUYER_LIST, FORWARDER_LIST, SHIP_MODES, SUPPLIER_LIST } from './salesConfig';

export { BUYER_LIST, FORWARDER_LIST, SHIP_MODES, SUPPLIER_LIST };

export const ORDER_TYPES = ['Bulk', 'Sample', 'Warehouse', 'Group'];
export const INVOICE_TYPES = ['Bulk', 'Packing List', 'Order'];
export const AGAINST_OPTIONS = ['Order', 'Packing List'];
export const ORDER_CAT_OPTIONS = ['Export', 'Domestic'];
export const CURRENCY_LIST = [
  { code: 'USD', symbol: '$', defaultRate: 83.50, factor: 1.0 },
  { code: 'EUR', symbol: '€', defaultRate: 90.20, factor: 1.0 },
  { code: 'GBP', symbol: '£', defaultRate: 106.00, factor: 1.0 },
  { code: 'INR', symbol: '₹', defaultRate: 1.00, factor: 1.0 },
];
export const CONSIGNEE_LIST = [
  'Consignee A - New York Warehouse',
  'Consignee B - London Logistics Hub',
  'Consignee C - Hamburg Distribution',
];
export const DELIVERY_ADDRESSES = [
  '123 Freight Logistics Way, Port of Newark, NJ 07114, USA',
  '789 Docklands Avenue, London E16 2AB, United Kingdom',
  'Hafenstrasse 42, 20457 Hamburg, Germany',
];

export const EXPORT_INVOICE_PER_PAGE = [5, 10, 20, 50];
export const EXPORT_INVOICE_DOWNLOAD_TYPES = ['csv', 'pdf', 'xls', 'rtf'];

export const EXPORT_INVOICE_COLUMNS = [
  { key: 'sno', label: 'S.No', searchable: false, width: '60px' },
  { key: 'exportInvNo', label: 'Export Inv No', searchable: true },
  { key: 'date', label: 'Date', searchable: true },
  { key: 'buyer', label: 'Buyer', searchable: true },
  { key: 'country', label: 'Country', searchable: true },
  { key: 'mode', label: 'Mode', searchable: true },
  { key: 'system', label: 'System', searchable: true },
  { key: 'currency', label: 'Currency', searchable: true },
  { key: 'exchangeRate', label: 'Ex. Rate', searchable: true },
  { key: 'invQty', label: 'Inv Qty', searchable: true },
  { key: 'invValue', label: 'Inv Value', searchable: true },
  { key: 'invValueINR', label: 'Inv Value (INR)', searchable: true },
  { key: 'orderNo', label: 'Order No', searchable: true },
  { key: 'refNo', label: 'Ref No', searchable: true },
  { key: 'despatchQty', label: 'Despatch Qty', searchable: true },
  { key: 'shipBillNo', label: 'Ship Bill No', searchable: true },
  { key: 'shipBillDate', label: 'Ship Bill Date', searchable: true },
  { key: 'billNo', label: 'Bill No', searchable: true },
  { key: 'billDate', label: 'Bill Date', searchable: true },
  { key: 'billRefNo', label: 'Bill Ref No', searchable: true },
  { key: 'billRefDate', label: 'Bill Ref Date', searchable: true },
  { key: 'icDate', label: 'IC Date', searchable: true },
  { key: 'dbkClaimed', label: 'DBK Claimed', searchable: true },
  { key: 'dbkReceived', label: 'DBK Received', searchable: true },
  { key: 'epCopyStatus', label: 'EP Copy Status', searchable: true },
  { key: 'epCopyNo', label: 'EP Copy No', searchable: true },
  { key: 'epCopyDate', label: 'EP Copy Date', searchable: true },
  { key: 'transporter', label: 'Transporter', searchable: true },
  { key: 'transInvNo', label: 'Trans Inv No', searchable: true },
  { key: 'transInvDate', label: 'Trans Inv Date', searchable: true },
  { key: 'transInvAmount', label: 'Trans Inv Amount', searchable: true },
  { key: 'invForwarder', label: 'Inv Forwarder', searchable: true },
  { key: 'forwarderInvNo', label: 'Forwarder Inv No', searchable: true },
  { key: 'forwarderInvDate', label: 'Forwarder Inv Date', searchable: true },
  { key: 'forwarderInvAmount', label: 'Forwarder Inv Amount', searchable: true },
  { key: 'brcNo', label: 'BRC No', searchable: true },
  { key: 'brcDate', label: 'BRC Date', searchable: true },
  { key: 'vesselName', label: 'Vessel Name', searchable: true },
  { key: 'etd', label: 'ETD', searchable: true },
  { key: 'eta', label: 'ETA', searchable: true },
  { key: 'preparedBy', label: 'Prepared By', searchable: true },
  { key: 'roslClaimed', label: 'ROSL Claimed', searchable: true },
  { key: 'roslReceived', label: 'ROSL Received', searchable: true },
  { key: 'meisClaimed', label: 'MEIS Claimed', searchable: true },
  { key: 'meisReceived', label: 'MEIS Received', searchable: true },
  { key: 'igstClaimed', label: 'IGST Claimed', searchable: true },
  { key: 'igstReceived', label: 'IGST Received', searchable: true },
  { key: 'action', label: 'Action', searchable: false, width: '110px' },
];

export const MOCK_EXPORT_INVOICES = [
  {
    id: 'expinv-101',
    exportInvNo: 'EXP-INV-2026-101',
    date: '2026-09-10',
    buyer: 'Nike Global Retail',
    country: 'USA',
    mode: 'Air',
    system: 'ERP-v2',
    currency: 'USD',
    exchangeRate: '83.50',
    invQty: '12500',
    invValue: '25000.00',
    invValueINR: '2087500.00',
    orderNo: 'ORD-2026-8801',
    refNo: 'REF-9901',
    despatchQty: '12500',
    shipBillNo: 'SB-88201',
    shipBillDate: '2026-09-11',
    billNo: 'BL-9901',
    billDate: '2026-09-12',
    billRefNo: 'BREF-101',
    billRefDate: '2026-09-12',
    icDate: '2026-09-13',
    dbkClaimed: '25000.00',
    dbkReceived: '25000.00',
    epCopyStatus: 'Done',
    epCopyNo: 'EP-55101',
    epCopyDate: '2026-09-13',
    transporter: 'VRL Logistics',
    transInvNo: 'TR-4401',
    transInvDate: '2026-09-10',
    transInvAmount: '45000.00',
    invForwarder: 'DHL Express Global',
    forwarderInvNo: 'FWD-8821',
    forwarderInvDate: '2026-09-11',
    forwarderInvAmount: '68000.00',
    brcNo: 'BRC-77101',
    brcDate: '2026-09-14',
    vesselName: 'Ever Given v.102',
    etd: '2026-09-15',
    eta: '2026-09-28',
    preparedBy: 'Admin / Documentation',
    roslClaimed: '12500.00',
    roslReceived: '12500.00',
    meisClaimed: '18000.00',
    meisReceived: '18000.00',
    igstClaimed: '375000.00',
    igstReceived: '375000.00',
    status: 'Done',
    against: 'Order',
    orderCat: 'Export',
    consignee: 'Consignee A - New York Warehouse',
    delAddress: '123 Freight Logistics Way, Port of Newark, NJ 07114, USA',
    items: [
      { id: 1, orderNo: 'ORD-2026-8801', date: '2026-09-01', jobOrderNo: 'JO-2026-8801', jobOrderDate: '2026-09-02', qty: '12500' }
    ]
  },
  {
    id: 'expinv-102',
    exportInvNo: 'EXP-INV-2026-102',
    date: '2026-09-12',
    buyer: 'Adidas Sourcing Ltd',
    country: 'Germany',
    mode: 'Sea',
    system: 'ERP-v2',
    currency: 'EUR',
    exchangeRate: '90.20',
    invQty: '8400',
    invValue: '18000.00',
    invValueINR: '1623600.00',
    orderNo: 'ORD-2026-8802',
    refNo: 'REF-9902',
    despatchQty: '8400',
    shipBillNo: 'SB-88202',
    shipBillDate: '2026-09-13',
    billNo: 'BL-9902',
    billDate: '2026-09-14',
    billRefNo: 'BREF-102',
    billRefDate: '2026-09-14',
    icDate: '2026-09-15',
    dbkClaimed: '19000.00',
    dbkReceived: '0.00',
    epCopyStatus: 'Pending',
    epCopyNo: 'EP-55102',
    epCopyDate: '2026-09-15',
    transporter: 'TCI Freight',
    transInvNo: 'TR-4402',
    transInvDate: '2026-09-12',
    transInvAmount: '38000.00',
    invForwarder: 'Maersk Logistics',
    forwarderInvNo: 'FWD-8822',
    forwarderInvDate: '2026-09-13',
    forwarderInvAmount: '52000.00',
    brcNo: 'BRC-77102',
    brcDate: '2026-09-16',
    vesselName: 'Maersk Line v.404',
    etd: '2026-09-18',
    eta: '2026-10-05',
    preparedBy: 'Documentation Team',
    roslClaimed: '9000.00',
    roslReceived: '0.00',
    meisClaimed: '14000.00',
    meisReceived: '0.00',
    igstClaimed: '290000.00',
    igstReceived: '0.00',
    status: 'Pending',
    against: 'Order',
    orderCat: 'Export',
    consignee: 'Consignee C - Hamburg Distribution',
    delAddress: 'Hafenstrasse 42, 20457 Hamburg, Germany',
    items: [
      { id: 1, orderNo: 'ORD-2026-8802', date: '2026-09-03', jobOrderNo: 'JO-2026-8802', jobOrderDate: '2026-09-04', qty: '8400' }
    ]
  }
];
